### ISSUE TITLE
Fill missing members for Records

### ISSUE THREAD

**Issue by michaelschufi** [tamj0rd2/ts-quickfixes#128]
Hi @tamj0rd2 

Thanks for this extension :-)

I frequently create mapping objects doing something similar to this:

```typescript
type MyUnionType = "some" | "strings";

interface MyInterface {
  field: "Foo" | "Bar" | "Foo Bar";
}

const myObject: Record<"foo", string> = {};
const myObject2: Record<MyInterface["field"], MyUnionType> = {};
```

But this is not yet supported.

This may have something to do with #122

**Comment by tamj0rd2** [comment]
Thanks for flagging this, I'll have a look into it!

**Comment by tamj0rd2** [comment]
![records](https://user-images.githubusercontent.com/20561445/114286109-cf8cb400-9a53-11eb-8100-e031744f612a.gif)

This is coming out in the next release of the extension which should be available at some point in the next day. Let me know if you have any issues

**Comment by michaelschufi** [comment]
Looks awesome :D Thank you! I will try it out tomorrow :)
