### ISSUE TITLE
Declare missing members for method calls

### ISSUE THREAD

**Issue by connorjclark** [tamj0rd2/ts-quickfixes#182]
This is similar to #77.

![image](https://user-images.githubusercontent.com/4071474/117406164-4f326500-aed2-11eb-9f53-cbe9b2d54145.png)

**Comment by connorjclark** [comment]
P.S. I don't know how I survive so long without this extension. Thank you so much!

**Comment by tamj0rd2** [comment]
I'm having a bit of trouble with github actions, but this change should hopefully be published by tomorrow.
