### ISSUE TITLE
Installation guide?

### ISSUE THREAD

**Issue by Norfeldt** [tamj0rd2/ts-quickfixes#219]
I seem to be doing something wrong. Install the plugin via the install and right clicked the variable - but saw no option to add missing members. I'm sure it's just something simple I have to do, but don't know what it is 🤔

<img width="837" alt="Screenshot 2021-06-14 at 13 24 09" src="https://user-images.githubusercontent.com/678806/121884981-e2518c80-cd13-11eb-9a5e-29b5136dd267.png">

<img width="423" alt="Screenshot 2021-06-14 at 13 23 57" src="https://user-images.githubusercontent.com/678806/121884990-e41b5000-cd13-11eb-9d31-af46057a6264.png">

**Comment by tamj0rd2** [comment]
When you hover over the variable that has the error and click the lightbulb, you should see a list of quick fixes to apply. There should be one called "Declare missing members". When you choose that, the fix should be applied. Here's a guide: https://code.visualstudio.com/docs/editor/refactoring

If it still doesn't work after that, could you please send me a code example and I'll have a look into what's wrong. But FYI, this feature is going to be available in Typescript soon, so if you give it a few weeks, you might not need this extension after all.

**Comment by Norfeldt** [comment]
The extension seems great 👍 . 

I'm in no rush and have way too many extensions, so I can wait a couple of weeks. Where did you read about this feature release in TypeScript?

**Comment by tamj0rd2** [comment]
> The extension seems great 👍 .
> 
> I'm in no rush and have way too many extensions, so I can wait a couple of weeks. Where did you read about this feature release in TypeScript?

https://github.com/microsoft/TypeScript/issues/28491

I saw this issue get closed and the corresponding PR
