### ISSUE TITLE
Add support for union types (ts2322)

### ISSUE THREAD

**Issue by GV94** [tamj0rd2/ts-quickfixes#349]
Currently the plugin does not work for ts2322, this is the error you get when trying to assign a non-matching type to a variable that is of a union type.

Example
```ts
type A  = {a: string}
type B = {b: string}
type C = A & B

export const myVar: C = {} //this will give you ts(2322)
````

![image](https://user-images.githubusercontent.com/8666502/154104945-ce404841-7886-4981-9bae-5a0648dc1078.png)

After experimenting a little bit with a fork, the plugin already seems to support ts2322 out of the box if the error code is just added to `supportedErrorCodes`  array in `plugin/src/code-fixes/declare-missing-object-members.ts`

I suggest doing this to add another scenario in which this plugin can be used.

**Comment by tamj0rd2** [comment]
Hey, I'm not maintaining this anymore. But I thought Typescript already had this functionality built in?

**Comment by tamj0rd2** [comment]
Hey, I'm not maintaining this anymore but if you submit a PR I'm happy to merge it

**Comment by tamj0rd2** [comment]
Closing as this hasn't had any activity
