### ISSUE TITLE
TS Quickfixes extension slows vscode

### ISSUE THREAD

**Issue by MHillier98** [tamj0rd2/ts-quickfixes#408]
Type: <b>Bug</b>

`Extension Bisect is done and has identified tamj0rd2.ts-quickfixes-extension as the extension causing the problem.`

VS Code becomes laggy when this extension is enabled - previously had no issues so I'm unsure why this is the case now.

Extension version: 1.15.0
VS Code version: Code 1.76.0 (Universal) (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:23:45.993Z)
OS version: Darwin x64 22.2.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|16, 14, 9|
|Memory (System)|32.00GB (0.16GB free)|
|Process Argv|--crash-reporter-id 0ae37222-f9e6-43c7-b4d9-63cb984361fa|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1:30587005
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
showlangstatbar:30672706
vsccsb:30677849
funwalk2:30676043

```

</details>

**Comment by tamj0rd2** [comment]
I'd suggest uninstalling this. I don't maintain it anymore and haven't done any work on it for any Typescript v4 releases.

**Comment by tamj0rd2** [comment]
Alternatively, if you can make a PR to fix the issue I'd be happy to merge it.
